
version: '3.9'

services:
  db:
    image: postgis/postgis:14-3.2-alpine
    container_name: eyewalk-postgres
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
  cache:
    image: redis:6.2.6-alpine
    container_name: eyewalk-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
